export const ACHIEVEMENTS_DATA = [
    {
        id: 'ach_0',
        icono: '🐣',
        nombre: '¡Nació el Pollito!',
        descEs: 'Haz tu primer click.',
        descEn: 'Make your first click.',
        condicion: ({ historico }) => historico >= 1,
        recompensa: { tipo: 'multiplicadorCps', valor: 1.1 },
        recompensaDescEs: 'CPS x1.1',
        recompensaDescEn: 'CPS x1.1',
    },
    {
        id: 'ach_1',
        icono: '🌾',
        nombreEs: 'Granjero Amateur',
        nombreEn: 'Amateur Farmer',
        descEs: 'Acumulá 1.000 semillas históricas.',
        descEn: 'Accumulate 1,000 historical seeds.',
        condicion: ({ historico }) => historico >= 1000,
        recompensa: { tipo: 'multiplicadorCps', valor: 1.25 },
        recompensaDescEs: 'CPS x1.25',
        recompensaDescEn: 'CPS x1.25',
    },
    {
        id: 'ach_2',
        icono: '🏪',
        nombreEs: 'Comprador Compulsivo',
        nombreEn: 'Compulsive Buyer',
        descEs: 'Comprá 10 ítems en total.',
        descEn: 'Buy 10 items in total.',
        condicion: ({ totalItems }) => totalItems >= 10,
        recompensa: { tipo: 'multiplicadorClick', valor: 1.5 },
        recompensaDescEs: 'Click x1.5',
        recompensaDescEn: 'Click x1.5',
    },
    {
        id: 'ach_3',
        icono: '🚜',
        nombreEs: 'Llegaste al Tier 2',
        nombreEn: 'Reached Tier 2',
        descEs: 'Desbloqueá tu primer ítem del Tier 2.',
        descEn: 'Unlock your first Tier 2 item.',
        condicion: ({ inventario }) => (inventario['item_20'] || 0) >= 1,
        recompensa: { tipo: 'multiplicadorCps', valor: 1.5 },
        recompensaDescEs: 'CPS x1.5',
        recompensaDescEn: 'CPS x1.5',
    },
    {
        id: 'ach_4',
        icono: '👑',
        nombreEs: 'Rey de la Granja',
        nombreEn: 'Farm King',
        descEs: 'Acumulá 1.000.000 semillas históricas.',
        descEn: 'Accumulate 1,000,000 historical seeds.',
        condicion: ({ historico }) => historico >= 1_000_000,
        recompensa: { tipo: 'multiplicadorClick', valor: 2 },
        recompensaDescEs: 'Click x2',
        recompensaDescEn: 'Click x2',
    },
];